### PR TITLE
Updates localization of admin modules to 9.6.0

### PR DESCRIPTION
**Pull request by valadas**
This PR corrects some typos, errors and
updates the localization as per the 9.6.0 release

### CODE REVIEW

**Comment by valadas** [comment]
@BravoSierra if you can let me know what you think about this

**Comment by donker** [comment]
This is a PR straight to master. Is that how it should be done? I thought we'd merge to develop first.

**Comment by valadas** [comment]
You are correct @donker let me fix that :)

**Comment by valadas** [comment]
Ok, so I had some stuff merged into master before the develop branch got changed to be the default and before we discussed about workflow. Please hold I need to take a look tomorrow to make sure we don't run into merge issues, I will ping you up again when double-checked...

**Comment by valadas** [comment]
Got into some issues, replaced with #6

**Pull request closed without merging**
